package com.zenus.gistreader.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.zenus.gistreader.dao.Gist;
import com.zenus.gistreader.dao.GistFile;
import com.zenus.gistreader.dao.OfflineCommand;

import com.zenus.gistreader.dao.GistDao;
import com.zenus.gistreader.dao.GistFileDao;
import com.zenus.gistreader.dao.OfflineCommandDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gistDaoConfig;
    private final DaoConfig gistFileDaoConfig;
    private final DaoConfig offlineCommandDaoConfig;

    private final GistDao gistDao;
    private final GistFileDao gistFileDao;
    private final OfflineCommandDao offlineCommandDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gistDaoConfig = daoConfigMap.get(GistDao.class).clone();
        gistDaoConfig.initIdentityScope(type);

        gistFileDaoConfig = daoConfigMap.get(GistFileDao.class).clone();
        gistFileDaoConfig.initIdentityScope(type);

        offlineCommandDaoConfig = daoConfigMap.get(OfflineCommandDao.class).clone();
        offlineCommandDaoConfig.initIdentityScope(type);

        gistDao = new GistDao(gistDaoConfig, this);
        gistFileDao = new GistFileDao(gistFileDaoConfig, this);
        offlineCommandDao = new OfflineCommandDao(offlineCommandDaoConfig, this);

        registerDao(Gist.class, gistDao);
        registerDao(GistFile.class, gistFileDao);
        registerDao(OfflineCommand.class, offlineCommandDao);
    }
    
    public void clear() {
        gistDaoConfig.getIdentityScope().clear();
        gistFileDaoConfig.getIdentityScope().clear();
        offlineCommandDaoConfig.getIdentityScope().clear();
    }

    public GistDao getGistDao() {
        return gistDao;
    }

    public GistFileDao getGistFileDao() {
        return gistFileDao;
    }

    public OfflineCommandDao getOfflineCommandDao() {
        return offlineCommandDao;
    }

}
